"""Generates docs/roadmap.md: a single, searchable table of every catalog
control with its implementation status.

The 160-control folder tree under `controls/` is a scaffold for future PRs,
not a browsing surface — this script produces one compact, Ctrl+F-friendly
page so a reader can survey the whole roadmap without opening folders.

Run after `scripts/scaffold_controls.py`, or whenever a control's Status
line changes, to keep docs/roadmap.md in sync:

    python scripts/generate_roadmap.py
"""

import re
from pathlib import Path

from scaffold_controls import CATEGORY_TO_GROUP, ROWS, slug

REPO_ROOT = Path(__file__).resolve().parent.parent
CONTROLS_ROOT = REPO_ROOT / "controls"
OUTPUT = REPO_ROOT / "docs" / "roadmap.md"
IMPLEMENTED_STATUS = re.compile(r"> \*\*Status:\*\* (?:Implemented|Validated)")


def status_and_link(group: str, control_id: str, control: str) -> tuple[str, str]:
    control_dir = CONTROLS_ROOT / group / f"{control_id}_{slug(control)}"
    readme = control_dir / "README.md"
    # Links are relative to docs/roadmap.md itself, not the repository root.
    relative = f"../{readme.relative_to(REPO_ROOT).as_posix()}"
    if readme.exists() and IMPLEMENTED_STATUS.search(readme.read_text(encoding="utf-8")):
        return "✅ Implemented", relative
    return "Planned", relative


def build() -> None:
    lines = [
        "<!-- generated by scripts/generate_roadmap.py; do not hand-edit -->",
        "# Control catalog roadmap",
        "",
        "A single-page, searchable index of all 160 governance controls in this",
        "repository. Use your browser's find (Ctrl+F / Cmd+F) to locate a control",
        "ID, category, or signal. Implemented controls link to their working demo;",
        "planned controls link to a scaffolded README with no implementation yet.",
        "",
        "For the curated set of runnable demos, start with",
        "[Recently added — community demos](../README.md#recently-added--community-demos)",
        "in the root README instead of this full roadmap.",
        "",
        "| Status | ID | Lifecycle phase | Category | Control / signal |",
        "|---|---|---|---|---|",
    ]
    for phase, control_id, category, control, *_rest in ROWS:
        group = CATEGORY_TO_GROUP[category]
        status, relative = status_and_link(group, control_id, control)
        lines.append(f"| {status} | [{control_id}]({relative}) | {phase} | {category} | {control} |")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    implemented = sum(1 for line in lines if line.startswith("| ✅"))
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}: {len(ROWS)} controls, {implemented} implemented.")


if __name__ == "__main__":
    build()
